#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════════════════
   import-check.cjs — Excel/CSV import and Jeeves export guard

     1. READER      .xlsx parsing against real DEFLATE fixtures: shared
                    strings, inline strings, dates, entities, decimals, and
                    line numbers that match what the user sees in Excel.
     2. CSV         delimiter sniffing, quoting, Nordic decimal commas, BOM.
     3. MAPPING     header aliases in both languages, missing/unknown columns.
     4. VALIDATION  every error and warning class, in both scopes.
     5. COMMIT      creates only non-error rows; ids do not collide.
     6. JEEVES      payload shape, totals reconcile against the payroll model.

   Fixtures live in fixtures/ and are regenerated by fixtures/make-fixtures.py.

   Exit 0 = clean.
   ═══════════════════════════════════════════════════════════════════════ */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const FIX = path.join(ROOT, 'fixtures');

const store = {};
global.localStorage = {
  getItem: k => (k in store ? store[k] : null),
  setItem: (k, v) => { store[k] = String(v); },
  removeItem: k => { delete store[k]; }
};

require(path.join(ROOT, 'ib-markets.js'));
const I  = require(path.join(ROOT, 'ib-i18n.js'));
const IB = require(path.join(ROOT, 'ib-core.js'));
const X  = require(path.join(ROOT, 'ib-xlsx.js'));
const IM = require(path.join(ROOT, 'ib-import.js'));

let failures = 0, checks = 0;
const red = s => `\x1b[31m${s}\x1b[0m`;
const green = s => `\x1b[32m${s}\x1b[0m`;
const dim = s => `\x1b[2m${s}\x1b[0m`;
const bold = s => `\x1b[1m${s}\x1b[0m`;

function ok(l, d) { checks++; console.log(`  ${green('PASS')} ${l}${d ? dim('  ' + d) : ''}`); }
function fail(l, e, a) {
  checks++; failures++;
  console.log(`  ${red('FAIL')} ${l}`);
  if (e !== undefined) { console.log(`       expected ${e}`); console.log(`       actual   ${a}`); }
}
function eq(l, actual, expected) {
  const a = JSON.stringify(actual), e = JSON.stringify(expected);
  if (a === e) ok(l, a.length < 60 ? a : undefined); else fail(l, e, a);
}
function near(l, a, e, tol) {
  if (Math.abs(a - e) <= (tol === undefined ? 0.01 : tol)) ok(l, String(IB.round2(a)));
  else fail(l, IB.round2(e), IB.round2(a));
}

const load = f => X.readTable({ name: f, bytes: new Uint8Array(fs.readFileSync(path.join(FIX, f))) });
const csv = (name, text) =>
  X.readTable({ name, bytes: new Uint8Array(Buffer.from(text, 'utf8')) });

(async () => {

  /* ═══════════════════ 1. READER ═══════════════════ */
  console.log(bold('\nREADER — .xlsx against real DEFLATE fixtures'));
  {
    const t = await load('dk-clean.xlsx');
    eq('sheet name read from workbook.xml', t.sheet, 'Løngrundlag');
    eq('headers (shared strings)', t.headers,
       ['Konsulent e-mail','Periode','Beskrivelse','Timer','Timeløn','Ydelse']);
    eq('numbers stay numbers', t.rows[0].cells[3], 37.5);
    eq('row count', t.rows.length, 3);

    const e = await load('dk-edge.xlsx');
    eq('XML entities unescaped', e.rows[0].cells[2], 'Tekst med "citat" & tegn <her>');
    eq('custom date format → ISO', e.rows[0].cells[1], '2026-05-01');
    eq('decimal rate', e.rows[0].cells[4], 520.5);

    const m = await load('no-messy.xlsx');
    eq('builtin date format → ISO', m.rows[0].cells[1], '2026-05-01');
    eq('inline string', m.rows[0].cells[2], 'Frontend-utvikling');
    eq('blank row skipped, line numbers match Excel',
       m.rows.map(r => r.line), [2, 3, 4, 5, 7]);
  }

  /* ═══════════════════ 2. CSV ═══════════════════ */
  console.log(bold('\nCSV — delimiters, quoting, Nordic numbers'));
  {
    const semi = await csv('a.csv', 'Konsulent e-mail;Periode;Timer;Timeløn\nsara@k.dk;Maj;37,5;520\n');
    eq('semicolon sniffed', semi.headers.length, 4);
    eq('decimal comma → number', semi.rows[0].cells[2], 37.5);

    const comma = await csv('b.csv', 'a,b,c\n1,2,3\n');
    eq('comma sniffed', comma.headers, ['a', 'b', 'c']);

    const tab = await csv('c.tsv', 'a\tb\n1\t2\n');
    eq('tab sniffed', tab.headers, ['a', 'b']);

    const q = await csv('d.csv', 'name;note\n"Lide, A/S";"sa ""hej"" da"\n');
    eq('quoted field with delimiter', q.rows[0].cells[0], 'Lide, A/S');
    eq('escaped quotes', q.rows[0].cells[1], 'sa "hej" da');

    const bom = await csv('e.csv', '﻿a;b\n1;2\n');
    eq('BOM stripped', bom.headers[0], 'a');

    const grouped = await csv('f.csv', 'x\n1 234,50\n');
    eq('space-grouped Nordic number', grouped.rows[0].cells[0], 1234.5);
  }

  /* ═══════════════════ 3. ERROR PATHS ═══════════════════ */
  console.log(bold('\nREADER — rejects what it cannot read'));
  for (const [name, bytes, expect] of [
    ['x.xlsx', new Uint8Array([1, 2, 3, 4]), 'NOT_A_WORKBOOK'],
    ['old.xls', new Uint8Array([0xd0, 0xcf, 0x11, 0xe0, 0, 0, 0, 0]), 'LEGACY_XLS'],
    ['empty.csv', new Uint8Array(0), 'EMPTY_FILE']
  ]) {
    try { await X.readTable({ name, bytes }); fail(`${name} should be rejected`, expect, 'no error'); }
    catch (e) { eq(`${name} → ${expect}`, e.message, expect); }
  }

  /* ═══════════════════ 4. MAPPING ═══════════════════ */
  console.log(bold('\nMAPPING — header aliases, both languages'));
  {
    const da = IM.mapColumns(['Konsulent e-mail','Periode','Beskrivelse','Timer','Timeløn','Ydelse'], 'company');
    eq('danish headers mapped', Object.keys(da.mapping).sort(),
       ['consultantEmail','description','hourlyRate','hours','period','type']);
    const nb = IM.mapColumns(['Konsulent e-post','Periode','Beskrivelse','Timer','Timelønn','Tjeneste'], 'company');
    eq('norwegian headers mapped', Object.keys(nb.mapping).sort(),
       ['consultantEmail','description','hourlyRate','hours','period','type']);

    const loose = IM.mapColumns(['E-post','MÅNED','Antall timer','Timesats','Kostnadssted'], 'company');
    eq('case/spelling variants mapped', Object.keys(loose.mapping).sort(),
       ['consultantEmail','hourlyRate','hours','period']);
    eq('unrecognised column reported, not fatal', loose.unknown, ['Kostnadssted']);

    const adminMissing = IM.mapColumns(['Konsulent e-mail','Periode','Timer','Timeløn'], 'admin');
    eq('admin scope requires a company column', adminMissing.missing, ['companyEmail']);
    const companyOk = IM.mapColumns(['Konsulent e-mail','Periode','Timer','Timeløn'], 'company');
    eq('company scope does not', companyOk.missing, []);
  }

  /* ═══════════════════ 5. VALIDATION ═══════════════════ */
  console.log(bold('\nVALIDATION — every issue class'));
  {
    IB.seedAll(); IB.setMarket('NO');
    const users = IB.getUsers();
    const company = users.find(u => u.email === 'info@bedrift.no');
    const t = await load('no-messy.xlsx');
    const v = IM.validate(t, { scope: 'company', users, company, existing: IB.getAssignments() });

    eq('summary', v.summary.total + '/' + v.summary.ok + '/' + v.summary.warning + '/' + v.summary.error,
       '5/1/2/2');
    const byLine = {};
    v.rows.forEach(r => { byLine[r.line] = r.issues.map(i => i.key); });
    eq('line 3 unknown consultant', byLine[3], ['import.err.consultantUnknown']);
    eq('line 4 negative hours', byLine[4], ['import.err.hoursRange']);
    eq('line 5 missing description', byLine[5], ['import.warn.descriptionDefaulted']);
    eq('line 7 unknown service type', byLine[7], ['import.warn.typeDefaulted']);
    eq('error rows carry no data', v.rows.filter(r => r.status === 'error').every(r => r.data === null), true);
    eq('warning rows still carry data', v.rows.find(r => r.line === 5).data !== null, true);
    eq('defaulted description falls back to period',
       v.rows.find(r => r.line === 5).data.description, 'Mai 2026');
    eq('defaulted type', v.rows.find(r => r.line === 7).data.type, IB.TYPE.EXCEL_IMPORT);

    // every issue key must be translatable in both languages
    const keys = new Set();
    v.rows.forEach(r => r.issues.forEach(i => keys.add(i.key)));
    const untranslated = [...keys].filter(k =>
      I.t(k, 'da').startsWith('⟦') || I.t(k, 'nb').startsWith('⟦'));
    eq('all issue keys translated in da and nb', untranslated, []);
  }

  /* ═══════════════════ 6. COMMIT ═══════════════════ */
  console.log(bold('\nCOMMIT — writes only what validated'));
  {
    IB.seedAll(); IB.setMarket('DK');
    const before = IB.getAssignments().length;
    const users = IB.getUsers();
    const company = users.find(u => u.email === 'info@virksomhed.dk');
    const t = await load('dk-clean.xlsx');
    const v = IM.validate(t, { scope: 'company', users, company, existing: IB.getAssignments() });
    const res = IM.commit(v, {});

    eq('created 3', res.created.length, 3);
    eq('skipped 0', res.skipped, 0);
    eq('stored', IB.getAssignments().length, before + 3);
    eq('all pending', res.created.every(a => a.status === IB.STATUS.PENDING), true);
    eq('tagged as import', res.created.every(a => a.source === 'excel-import'), true);
    eq('share one batch id', new Set(res.created.map(a => a.importBatch)).size, 1);
    eq('ids unique', new Set(res.created.map(a => a.id)).size, 3);
    eq('ids use the market prefix', res.created.every(a => a.id.startsWith('OPG-')), true);
    eq('consultant email carried for Jeeves keying',
       res.created[0].consultantEmail, 'sara@konsulent.dk');
    near('amount = hours × rate', res.created[0].amount,
         res.created[0].hours * res.created[0].hourlyRate, 0.000001);

    // re-importing the same file must be caught as duplicates, not silently doubled
    const v2 = IM.validate(t, { scope: 'company', users, company, existing: IB.getAssignments() });
    eq('re-import flags every row as a duplicate', v2.summary.warning, 3);
    eq('and none as clean', v2.summary.ok, 0);

    // error rows are skipped, never coerced
    IB.setMarket('NO');
    const nu = IB.getUsers();
    const nc = nu.find(u => u.email === 'info@bedrift.no');
    const mt = await load('no-messy.xlsx');
    const mv = IM.validate(mt, { scope: 'company', users: nu, company: nc, existing: IB.getAssignments() });
    const mres = IM.commit(mv, {});
    eq('messy file: 3 created, 2 skipped',
       mres.created.length + '/' + mres.skipped, '3/2');
  }

  /* ═══════════════════ 7. ADMIN SCOPE ═══════════════════ */
  console.log(bold('\nADMIN SCOPE — cross-company'));
  {
    IB.seedAll(); IB.setMarket('DK');
    const users = IB.getUsers();
    const t = await load('dk-admin.xlsx');
    const v = IM.validate(t, { scope: 'admin', users, existing: IB.getAssignments() });
    eq('both rows valid', v.summary.ok, 2);
    eq('routed to different companies',
       v.rows.map(r => r.data.companyName),
       ['Lides Event A/S', 'Prisjakt Danmark A/S']);

    const noCompanyCol = await load('dk-clean.xlsx');
    const v2 = IM.validate(noCompanyCol, { scope: 'admin', users });
    eq('file without company column is fatal in admin scope', v2.fatal, 'MISSING_COLUMNS');

    // an unknown company is an error, not a silent create
    const bad = await csv('bad.csv',
      'Virksomhed e-mail;Konsulent e-mail;Periode;Timer;Timeløn\n' +
      'nobody@nowhere.dk;sara@konsulent.dk;Maj 2026;10;500\n');
    const v3 = IM.validate(bad, { scope: 'admin', users });
    eq('unknown company rejected', v3.rows[0].issues[0].key, 'import.err.companyUnknown');
  }

  /* ═══════════════════ 8. JEEVES ═══════════════════ */
  console.log(bold('\nJEEVES — payload and reconciliation'));
  {
    IB.seedAll(); IB.setMarket('DK');
    const paid = IB.getAssignments().filter(a => a.status === IB.STATUS.PAID);
    const j = IM.toJeeves(paid);

    eq('format version', j.format, 'jeeves-payroll-batch-v1');
    eq('mapping flagged unverified', j.mappingVerified, false);
    eq('market stamped', j.market, 'DK');
    eq('legal entity stamped', j.legalEntity, 'Invoicery Business A/S');
    eq('currency stamped', j.currency, 'DKK');
    eq('row count', j.rowCount, paid.length);

    const r = j.rows[0];
    ['companyCode','assignmentId','employeeRef','employeeName','period','wageType',
     'quantity','unitPrice','invoiceAmount','grossSalary','netSalary','currency']
      .forEach(f => {
        if (r[f] === undefined || r[f] === null) fail(`row field ${f} present`, 'a value', 'undefined');
      });
    ok('every expected row field present', Object.keys(r).length + ' fields');

    // totals must reconcile against the payroll model, not be recomputed
    const model = IB.calcPayrollBatch(paid);
    near('invoice total reconciles', j.totals.invoiceAmount, model.invoiceAmount, 0.02);
    near('gross total reconciles', j.totals.grossSalary, model.gross, 0.02);
    near('net total reconciles', j.totals.netSalary, model.net, 0.02);
    near('employer cost reconciles', j.totals.employerCost, model.employerCost, 0.02);

    const csvOut = IM.toJeevesCSV(paid);
    eq('CSV starts with a BOM so Excel reads UTF-8', csvOut.charCodeAt(0), 0xfeff);
    eq('CSV is semicolon-separated', csvOut.split('\r\n')[0].includes(';'), true);
    eq('CSV row count matches', csvOut.trim().split('\r\n').length, paid.length + 1);

    const send = await IM.sendToJeeves(paid);
    eq('send refuses without a configured endpoint', send.reason, 'NO_ENDPOINT');
    eq('and still returns the payload for inspection', !!send.payload, true);

    // Norway produces its own currency and entity
    IB.setMarket('NO');
    const jno = IM.toJeeves(IB.getAssignments().filter(a => a.status === IB.STATUS.PAID));
    eq('NO currency', jno.currency, 'NOK');
    eq('NO entity', jno.legalEntity, 'Invoicery Business AS');
    eq('NO company code', jno.rows[0].companyCode, 'IBNO');
  }

  /* ═══════════════════ 9. TEMPLATE ═══════════════════ */
  console.log(bold('\nTEMPLATE — round-trips through the reader'));
  {
    for (const [scope, lang] of [['company','da'], ['admin','da'], ['company','nb'], ['admin','nb']]) {
      const text = IM.templateCSV(scope, lang);
      const t = await csv('template.csv', text);
      const m = IM.mapColumns(t.headers, scope);
      if (m.missing.length) fail(`${scope}/${lang} template maps cleanly`, '[]', JSON.stringify(m.missing));
      else ok(`${scope}/${lang} template maps cleanly`, t.headers.length + ' columns');
    }
  }

  console.log('');
  if (failures === 0) { console.log(green(bold(`  ${checks} checks passed.`))); process.exit(0); }
  console.log(red(bold(`  ${failures} of ${checks} checks FAILED.`)));
  process.exit(1);

})().catch(e => {
  console.error(red('\n  Harness error: ' + e.message));
  console.error(e.stack);
  process.exit(1);
});
